### ISSUE TITLE
org.apache.commons.codec.binary.Base64 conflict

### ISSUE THREAD

**Issue by mrgren** [getsentry/raven-java#137]
java.lang.NoSuchMethodError: No direct method <init>(Z)V in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/ext.jar)
            at org.apache.commons.codec.binary.Base64OutputStream.<init>(Base64OutputStream.java:65)
            at org.apache.commons.codec.binary.Base64OutputStream.<init>(Base64OutputStream.java:52)
            at net.kencochrane.raven.marshaller.json.JsonMarshaller.marshall(JsonMarshaller.java:95)
            at net.kencochrane.raven.connection.HttpConnection.doSend(HttpConnection.java:104)
            at net.kencochrane.raven.connection.AbstractConnection.send(AbstractConnection.java:78)
            at net.kencochrane.raven.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:148)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by mrgren** [comment]
# i use raven 4.0 but this issue was fixed on 6.0.0
