### ISSUE TITLE
JUL does not allow setting DSN via properties

### ISSUE THREAD

**Issue by dcramer** [getsentry/raven-java#140]
It looks like this might be a mishap with the JUL implementation:

Raven Version: 6.0.0

WildFly Version: 8.1.0.Final

Java Version: 1.7

Logging Properties

```
logger.level=WARN
logger.handlers=SENTRY
handler.SENTRY=net.kencochrane.raven.jul.SentryHandler
handler.SENTRY.properties=net.kencochrane.raven.jul.SentryHandler.dsn,handler.SENTRY.net.kencochrane.raven.jul.SentryHandler.tags
handler.SENTRY.net.kencochrane.raven.jul.SentryHandler.dsn=https://publicKey:secretKey@app.getsentry.com/<appId>
handler.SENTRY.net.kencochrane.raven.jul.SentryHandler.tags=tag1:value1,tag2:value2
```

WildFly Stacktrace

```
10:41:39,765 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-3) MSC000001: Failed to start service jboss.deployment.unit."app-web.war".POST_MODULE: org.jboss.msc.service.StartException in service jboss.deployment.unit."app-web.war".POST_MODULE: JBAS018733: Failed to process phase POST_MODULE of deployment “app-web.war"
at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:166) [wildfly-server-8.1.0.Final.jar:8.1.0.Final]
at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_67]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_67]
at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_67]

Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: JBAS011555: Failed to configure logging using 'logging.properties' configuration file.
at org.jboss.as.logging.deployments.LoggingConfigDeploymentProcessor.configure(LoggingConfigDeploymentProcessor.java:253)
at org.jboss.as.logging.deployments.LoggingConfigDeploymentProcessor.processDeployment(LoggingConfigDeploymentProcessor.java:111)
at org.jboss.as.logging.deployments.AbstractLoggingDeploymentProcessor.deploy(AbstractLoggingDeploymentProcessor.java:67)
at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:159) [wildfly-server-8.1.0.Final.jar:8.1.0.Final]

... 5 more

Caused by: java.lang.IllegalArgumentException: No property "net.kencochrane.raven.jul.SentryHandler.dsn" setter found for handler "SENTRY"
at org.jboss.logmanager.config.AbstractPropertyConfiguration.setPropertyValueExpression(AbstractPropertyConfiguration.java:196) [jboss-logmanager-1.5.2.Final.jar:1.5.2.Final]
at org.jboss.logmanager.config.AbstractPropertyConfiguration.setPropertyValueString(AbstractPropertyConfiguration.java:157) [jboss-logmanager-1.5.2.Final.jar:1.5.2.Final]
at org.jboss.logmanager.PropertyConfigurator.configureProperties(PropertyConfigurator.java:750) [jboss-logmanager-1.5.2.Final.jar:1.5.2.Final]
at org.jboss.logmanager.PropertyConfigurator.configureHandler(PropertyConfigurator.java:721) [jboss-logmanager-1.5.2.Final.jar:1.5.2.Final]
at org.jboss.logmanager.PropertyConfigurator.configureLogger(PropertyConfigurator.java:579) [jboss-logmanager-1.5.2.Final.jar:1.5.2.Final]
at org.jboss.logmanager.PropertyConfigurator.configure(PropertyConfigurator.java:517) [jboss-logmanager-1.5.2.Final.jar:1.5.2.Final]
at org.jboss.as.logging.deployments.LoggingConfigDeploymentProcessor.configure(LoggingConfigDeploymentProcessor.java:247)

... 8 more

10:41:50,785 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) JBAS014613: Operation ("deploy") failed - address: ([("deployment" => "app-web.war")]) - failure description: {"JBAS014671: Failed services" => {"jboss.deployment.unit.\"app-web.war\".POST_MODULE" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"app-web.war\".POST_MODULE: JBAS018733: Failed to process phase POST_MODULE of deployment \"app-web.war\"

Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: JBAS011555: Failed to configure logging using 'logging.properties' configuration file.

Caused by: java.lang.IllegalArgumentException: No property \"net.kencochrane.raven.jul.SentryHandler.dsn\" setter found for handler \"SENTRY\""}}
```

**Comment by dcramer** [comment]
Of note, and not explicitly related, it was reported that setting SENTRY_DSN in the env didn't work. I haven't confirmed if that would be problematic here or not.

**Comment by ColinHebert** [comment]
Could you put the entire configuration here? Also is it possible to check which version of Raven that person is running?

**Comment by dcramer** [comment]
@ColinHebert I've updated the ticket w/ more details

**Comment by arunshankerprasad** [comment]
Hi @dcramer,

Any update regarding this issue? We are still not able to integrate this to our application.

**Comment by JimHaughwout** [comment]
@dcramer Any word on this. We'd like to use Sentry to monitor Errors in WildFly-based apps.

**Comment by dcramer** [comment]
We haven't actually had time to look into this yet. We're planning to tackle some of the Java backlog soon, but if anyone has time before we get to it we're happy to provide guidance.

**Comment by giilby** [comment]
@dcramer #174 should fix this issue!

**Comment by bretthoerner** [comment]
https://github.com/getsentry/raven-java/commit/25fd367ffc44c47f141fb6a654bc693294710b33

**Comment by Winandvdb** [comment]
I'm getting this same issue with the new version of sentry-java. I'm using wildfly 10 and I'm trying to configure the SentryHandler as a custom-handler in the standalone config:

```
<custom-handler name="SENTRY" class="io.sentry.jul.SentryHandler" module="io.sentry">
                <formatter>
                    <named-formatter name="COLOR-PATTERN"/>
                </formatter>
                <properties>
                    <property name="dsn" value="https://publicKey:secretKey@app.getsentry.com"/>
                    <property name="release" value="1.0.0"/>
                    <property name="servername" value="dev"/>
                    <property name="stacktrace.app.packages" value="com.company"/>
                    <property name="environment" value="development"/>
                </properties>
</custom-handler>
```
I get this error:
```
java.lang.IllegalArgumentException: No property "dsn" setter found for handler "SENTRY"
	at org.jboss.logmanager.config.AbstractPropertyConfiguration.setPropertyValueExpression(AbstractPropertyConfiguration.java:193) [jboss-logmanager-2.0.4.Final.jar:2.0.4.Final]
	at org.jboss.logmanager.config.AbstractPropertyConfiguration.setPropertyValueString(AbstractPropertyConfiguration.java:154) [jboss-logmanager-2.0.4.Final.jar:2.0.4.Final]
	at org.jboss.as.logging.HandlerOperations.handleProperty(HandlerOperations.java:716)
	at org.jboss.as.logging.HandlerOperations.handleProperty(HandlerOperations.java:604)
	at org.jboss.as.logging.HandlerOperations.access$000(HandlerOperations.java:83)
	at org.jboss.as.logging.HandlerOperations$HandlerAddOperationStepHandler.performRuntime(HandlerOperations.java:273)
	at org.jboss.as.logging.LoggingOperations$LoggingAddOperationStepHandler$1.execute(LoggingOperations.java:204)
	at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:890) [wildfly-controller-2.2.0.Final.jar:2.2.0.Final]
	at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:659) [wildfly-controller-2.2.0.Final.jar:2.2.0.Final]
	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:370) [wildfly-controller-2.2.0.Final.jar:2.2.0.Final]
	at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1329) [wildfly-controller-2.2.0.Final.jar:2.2.0.Final]
	at org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:493) [wildfly-controller-2.2.0.Final.jar:2.2.0.Final]
	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:387) [wildfly-controller-2.2.0.Final.jar:2.2.0.Final]
	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:349) [wildfly-controller-2.2.0.Final.jar:2.2.0.Final]
	at org.jboss.as.server.ServerService.boot(ServerService.java:397) [wildfly-server-2.2.0.Final.jar:2.2.0.Final]
	at org.jboss.as.server.ServerService.boot(ServerService.java:366) [wildfly-server-2.2.0.Final.jar:2.2.0.Final]
	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:299) [wildfly-controller-2.2.0.Final.jar:2.2.0.Final]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_121]
```

Do I have to set the DSN in a different way with the new version of Sentry-Java? I have looked everywhere for a way to get Sentry working with Wildfly but nothing has worked so far and most examples still use Raven.

Any help would be amazing!

**Comment by bretthoerner** [comment]
Yes, configuration is done outside of the logging appender itself now.

Described some here: https://docs.sentry.io/clients/java/migration/#logging-integration-configuration
And different ways to configured are described at the top here: https://docs.sentry.io/clients/java/config/#configuration

**Comment by Winandvdb** [comment]
Thanks for the quick answer! 

However, I have already set up the configuration for Sentry.
My sentry properties in the system properties are as follows:
 ```
<system-properties>
  ...
  <property name="sentry.dsn" value="https://publicKey:secretKey@app.getsentry.com"/>
  <property name="sentry.release" value="1.0.0"/>
  <property name="sentry.servername" value="dev"/>
  <property name="sentry.stacktrace.app.packages" value="com.company"/>
  <property name="sentry.environment" value="development"/>
</system-properties>
```
And I am able to send messages to Sentry manually using Sentry.capture();, but the logs generated by Wildfly with java.util.logging are not sent to Sentry. Am I missing something? 

Is there a way to check if the SentryHandler is receiving anything?

**Comment by bretthoerner** [comment]
I see. Well you can leave out the `<properties>` bit in the handler config -- the handler will look up the system properties to configure itself.

Sentry (and the logging integrations) do a bit of logging at DEBUG level. You could turn that on and grep for `io.sentry` to see if the handler is doing anything.

That said, I don't know a lot about WildFly. When I looked [here](https://docs.jboss.org/author/display/WFLY10/How+To) though it's talking about log4j. Should you be using `io.sentry.log4j.SentryAppender`?
