### ISSUE TITLE
Scala, log4j2: An exception occurred while closing the Raven connection

### ISSUE THREAD

**Issue by phamlequang** [getsentry/raven-java#148]
I used scala and raven log4j2, but an error occurred while closing raven connection:
```
log4j:WARN No appenders could be found for logger (net.kencochrane.raven.RavenFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2015-09-07 15:55:16,189 ERROR An exception occurred while closing the Raven connection java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
	at java.lang.Runtime.removeShutdownHook(Runtime.java:239)
	at net.kencochrane.raven.connection.AsyncConnection.close(AsyncConnection.java:92)
	at net.kencochrane.raven.Raven.closeConnection(Raven.java:112)
	at net.kencochrane.raven.log4j2.SentryAppender.stop(SentryAppender.java:303)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.stop(AbstractConfiguration.java:237)
	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:224)
	at org.apache.logging.log4j.core.LoggerContext$1.run(LoggerContext.java:185)
	at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry$1.run(DefaultShutdownCallbackRegistry.java:100)
	at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.run(DefaultShutdownCallbackRegistry.java:74)
	at java.lang.Thread.run(Thread.java:745)
```
Here's my code:
```
import org.apache.logging.log4j.LogManager
object RunTransform {
    def main(args: Array[String]): Unit = {
        val logger = LogManager.getLogger("RunTransform")
        try {
            1/0
        } catch {
            case e: Exception => {
                logger.error("Exception caught", e)
            }
        }
     }
}
```

Here's log4j2.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration status="warn" packages="org.apache.logging.log4j.core,net.kencochrane.raven.log4j2">
    <appenders>
        <Raven name="Sentry">
            <dsn>
                http://my-key@my-domain/2?options
            </dsn>
            <tags>
                tag1:value1,tag2:value2
            </tags>
            <!--
                Optional, allows to select the ravenFactory
            -->
            <!--
            <ravenFactory>
                net.kencochrane.raven.DefaultRavenFactory
            </ravenFactory>
            -->
        </Raven>
    </appenders>

    <loggers>
        <root level="all">
            <appender-ref ref="Sentry"/>
        </root>
    </loggers>
</configuration>
```

**Comment by artyomboyko** [comment]
+1

**Comment by tkaemming** [comment]
This should be harmless. I added some details in this issue, and will track any changes there: #167.
