### ISSUE TITLE
Raven java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by mrgren** [getsentry/raven-java#150]
09-17 14:32:05.328   13737-9374/? E/AndroidRuntime﹕ FATAL EXCEPTION: raven-pool-1532-thread-1
    Process: io.pack.readlog, PID: 13737
    java.lang.OutOfMemoryError
            at java.util.zip.Deflater.createStream(Native Method)
            at java.util.zip.Deflater.<init>(Deflater.java:191)
            at java.util.zip.Deflater.<init>(Deflater.java:165)
            at java.util.zip.DeflaterOutputStream.<init>(DeflaterOutputStream.java:54)
            at net.kencochrane.raven.marshaller.json.JsonMarshaller.marshall(JsonMarshaller.java:107)
            at net.kencochrane.raven.connection.HttpConnection.doSend(HttpConnection.java:122)
            at net.kencochrane.raven.connection.AbstractConnection.send(AbstractConnection.java:78)
            at net.kencochrane.raven.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:137)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by dcramer** [comment]
I'm not entirely sure what we can do here. We definitely use some memory to send events, but we're likely not the actual cause of the OOM. In PHP we're able to define some crud variable to effectively reserve memory space for ourselves.

**Comment by tkaemming** [comment]
@mrgren - In the (unlikely) case that you're OOMing due to a large volume of messages being queued to be sent to the Sentry server, you can set the [`raven.async.queuesize`](https://github.com/getsentry/raven-java#async-connection) option to put an upper bound on the number of messages that will be kept in memory, with [older ones being discarded](https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/net/kencochrane/raven/DefaultRavenFactory.java#L141).

In the (again, unlikely) case that this is actually due to Raven, this probably means one (or more) of a few things:

- you are trying to send too much data to Sentry (messages are too large, and there is a reasonable probability that they would be rejected by the Sentry server for being too large),
- you are trying to send too many events to Sentry (errors are being generated at a higher rate than they can be accepted by the server.)
