### ISSUE TITLE
Java error: NoClassDefFoundError

### ISSUE THREAD

**Issue by kutenai** [getsentry/raven-java#159]
I've tried to follow the setup steps carefully, but when the code actually tries to log, I get an error:

```
Exception in thread "raven-pool-2-thread-7" java.lang.NoClassDefFoundError: com/google/common/io/BaseEncoding
	at net.kencochrane.raven.marshaller.json.JsonMarshaller.marshall(JsonMarshaller.java:107)
	at net.kencochrane.raven.connection.HttpConnection.doSend(HttpConnection.java:122)
	at net.kencochrane.raven.connection.AbstractConnection.send(AbstractConnection.java:78)
	at net.kencochrane.raven.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:137)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
```

I've setup the dependencies using maven
```
        <dependency>
            <groupId>net.kencochrane.raven</groupId>
            <artifactId>raven-log4j</artifactId>
            <version>6.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>18.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava-io</artifactId>
            <version>r03</version>
        </dependency>

```

Note that I explicitly added guava and guava-io, attempting to resolve this. Presumably these should be already in the dependencies.

I am using slf4j for logging.

Any insight would be much appreciated.

Ed

**Comment by tkaemming** [comment]
@kutenai - I wasn't able to replicate the issue on a [demonstration project](https://github.com/getsentry/raven-java-examples/tree/master/raven-java-log4j-example). Here is the resulting dependency tree from `mvn dependency:tree`, showing that Guava 18.0 is in the dependencies:

```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ raven-java-log4j2-example ---
[INFO] com.getsentry:raven-java-log4j2-example:jar:1.0-SNAPSHOT
[INFO] \- net.kencochrane.raven:raven-log4j:jar:6.0.0:compile
[INFO]    +- net.kencochrane.raven:raven:jar:6.0.0:compile
[INFO]    |  +- org.slf4j:slf4j-api:jar:1.7.9:compile
[INFO]    |  \- com.fasterxml.jackson.core:jackson-core:jar:2.5.0:compile
[INFO]    +- log4j:log4j:jar:1.2.17:compile
[INFO]    \- com.google.guava:guava:jar:18.0:compile
```

This looks maybe like a classpath issue? I'm going to close this since it doesn't look there is anything directly actionable for us to do here, but if you find something on the contrary, let us know and we'd be happy to reopen.

**Comment by tkaemming** [comment]
A similar issue was noted here, which turned out to be a versioning issue: https://github.com/agorapulse/grails-raven/issues/4#issuecomment-72265379
