### ISSUE TITLE
An exception occurred while closing the Raven connection java.lang.IllegalStateException: Shutdown in progress

### ISSUE THREAD

**Issue by artyomboyko** [getsentry/raven-java#165]
My code:

```
package com.example;

import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;

public class Main {
    private static final Logger logger = LogManager.getLogger(Main.class);

    public static void main(String[] args) {
        logger.error("Random error");
        logger.trace("Exiting application.");
    }
}
```

Getting:
```
2015-12-13 16:57:56,897 pool-1-thread-1 ERROR An exception occurred while closing the Raven connection java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
	at java.lang.Runtime.removeShutdownHook(Runtime.java:239)
	at net.kencochrane.raven.connection.AsyncConnection.close(AsyncConnection.java:92)
	at net.kencochrane.raven.Raven.closeConnection(Raven.java:112)
	at net.kencochrane.raven.log4j2.SentryAppender.stop(SentryAppender.java:303)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.stop(AbstractConfiguration.java:313)
	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:303)
	at org.apache.logging.log4j.core.LoggerContext$1.run(LoggerContext.java:262)
	at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry$1.run(DefaultShutdownCallbackRegistry.java:100)
	at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.run(DefaultShutdownCallbackRegistry.java:74)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by artyomboyko** [comment]
Setting raven.async.gracefulshutdown didn't helped

**Comment by artyomboyko** [comment]
@tkaemming help me :)

**Comment by artyomboyko** [comment]
I'm new to java, but it looks like a bug

https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/net/kencochrane/raven/connection/AsyncConnection.java#L92

We don't need to removeShutdownHook if this.gracefulShutdown is false.

Do you agree guys ?

**Comment by tkaemming** [comment]
@artyomboyko - I think that the patch in #166 will fix the symptom of the issue that you are encountering by removing the call to [`Runtime.removeShutdownHook`](https://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html#removeShutdownHook(java.lang.Thread)).

However, I think the root cause here is a different issue. [`SentryAppender.stop`](https://github.com/getsentry/raven-java/blob/master/raven-log4j2/src/main/java/net/kencochrane/raven/log4j2/SentryAppender.java#L296) is called as part of the log4j2 shutdown hook (see the bits about `DefaultShutdownCallbackRegistry` in the traceback above), at which point mutating the Runtime shutdown hooks will throw an [`IllegalStateException`](https://docs.oracle.com/javase/7/docs/api/java/lang/IllegalStateException.html).
