### ISSUE TITLE
Uncaught UnknownHostException in host lookup

### ISSUE THREAD

**Issue by karlgoldstein** [getsentry/raven-java#168]
Seeing this exception frequently in our logs (running a JVM in a Docker 1.7 container).  

time=2015-12-16T05:17:15.589Z level=WARN logger=net.kencochrane.raven.event.EventBuilder$HostnameCache task=us-west-2-zin-uat-batch-fetcher message="Localhost hostname lookup failed, keeping the value 'unavailable'" exception=java.net.UnknownHostException: a9c6d0d6a85e: a9c6d0d6a85e: unknown error class=java.util.concurrent.ExecutionException	java.net.UnknownHostException: a9c6d0d6a85e: unknown error
		at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_66]
		at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[na:1.8.0_66]
		at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[na:1.8.0_66]
		at java.net.InetAddress.getLocalHost(InetAddress.java:1500) ~[na:1.8.0_66]
		... 4 common frames omitted
	Wrapped by: java.net.UnknownHostException: a9c6d0d6a85e: a9c6d0d6a85e: unknown error
		at java.net.InetAddress.getLocalHost(InetAddress.java:1505) ~[na:1.8.0_66]
		at net.kencochrane.raven.event.EventBuilder$HostnameCache$HostRetriever.call(EventBuilder.java:572) ~[batch-fetcher-come_together.jar:come_together]
		at net.kencochrane.raven.event.EventBuilder$HostnameCache$HostRetriever.call(EventBuilder.java:569) ~[batch-fetcher-come_together.jar:come_together]
		at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_66]
		... 1 common frames omitted
	Wrapped by: java.util.concurrent.ExecutionException: java.net.UnknownHostException: a9c6d0d6a85e: a9c6d0d6a85e: unknown error
		at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.8.0_66]
		at java.util.concurrent.FutureTask.get(FutureTask.java:206) [na:1.8.0_66]
		at net.kencochrane.raven.event.EventBuilder$HostnameCache.updateCache(EventBuilder.java:557) [batch-fetcher-come_together.jar:come_together]
		at net.kencochrane.raven.event.EventBuilder$HostnameCache.getHostname(EventBuilder.java:543) [batch-fetcher-come_together.jar:come_together]
		at net.kencochrane.raven.event.EventBuilder.autoSetMissingValues(EventBuilder.java:87) [batch-fetcher-come_together.jar:come_together]
		at net.kencochrane.raven.event.EventBuilder.build(EventBuilder.java:297) [batch-fetcher-come_together.jar:come_together]
		at net.kencochrane.raven.logback.SentryAppender.buildEvent(SentryAppender.java:207) [batch-fetcher-come_together.jar:come_together]
		at net.kencochrane.raven.logback.SentryAppender.append(SentryAppender.java:132) [batch-fetcher-come_together.jar:come_together]
		at net.kencochrane.raven.logback.SentryAppender.append(SentryAppender.java:26) [batch-fetcher-come_together.jar:come_together]
		at ch.qos.logback.core.AppenderBase.doAppend(AppenderBase.java:85) [batch-fetcher-come_together.jar:come_together]
		at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:48) [batch-fetcher-come_together.jar:come_together]
		at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:273) [batch-fetcher-come_together.jar:come_together]
		at ch.qos.logback.classic.Logger.callAppenders(Logger.java:260) [batch-fetcher-come_together.jar:come_together]
		at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:442) [batch-fetcher-come_together.jar:come_together]
		at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:396) [batch-fetcher-come_together.jar:come_together]
		at ch.qos.logback.classic.Logger.error(Logger.java:555) [batch-fetcher-come_together.jar:come_together]

**Comment by tkaemming** [comment]
This is thrown when attempting to retrieve the hostname as part of [`EventBuilder`](https://github.com/getsentry/raven-java/blob/4a40e28cc92f32c397588a2e6a5e1bec3bd294e7/raven/src/main/java/net/kencochrane/raven/event/EventBuilder.java#L607) with [`java.net.InetAddress.getLocalHost`](https://docs.oracle.com/javase/7/docs/api/java/net/InetAddress.html#getLocalHost()) and is an issue with your networking configuration, not Raven.
