### ISSUE TITLE
java.lang.ClassCastException: net.kencochrane.raven.log4j.SentryAppender cannot be cast to org.apache.log4j.Appender

### ISSUE THREAD

**Issue by quantonganh** [getsentry/raven-java#169]
I'm trying to send [youtrack](https://www.jetbrains.com/youtrack/)'s exception to the [Sentry](https://github.com/getsentry/sentry).

`/etc/youtrack/log4j.xml`:

    <appender name="sentry" class="net.kencochrane.raven.log4j.SentryAppender">
      <param name="dsn" value="https://publicKey:secretKey@host:port/1"/>
      <filter class="org.apache.log4j.varia.LevelRangeFilter">
        <param name="levelMin" value="WARN"/>
      </filter>
    </appender>

    <root>
        <priority value="INFO"/>
        <appender-ref ref="SYSLOG"/>
        <appender-ref ref="sentry"/>
    </root>

A part of the original upstart file:

> exec java -Xmx{{ heap_size }} -XX:MaxPermSize=250m
> -Djava.awt.headless=true -Djetbrains.youtrack.disableBrowser=true -Djava.security.egd=/dev/zrandom -Djetbrains.mps.webr.log4jPath=/etc/youtrack/log4j.xml -jar /usr/local/youtrack/{{ jarfile }} 8082

and I changed it to:

> exec java -Xmx1g -XX:MaxPermSize=250m -Djava.awt.headless=true
> -Djetbrains.youtrack.disableBrowser=true -Djava.security.egd=/dev/zrandom -Djetbrains.mps.webr.log4jPath=/etc/youtrack/log4j.xml -cp /usr/local/youtrack/youtrack-6.5.16853.jar:/usr/local/youtrack/lib/*
> jetbrains.youtrack.standalone.YoutrackStandalone 8082

    
to specify the classpath (`/usr/local/youtrack/lib/*`).

Without copying `raven-log4j-6.0.0.jar` to `/usr/local/youtrack/lib`, I will get an error like this:

    log4j: Class name: [net.kencochrane.raven.log4j.SentryAppender]
    log4j:ERROR Could not create an Appender. Reported error follows.
    java.lang.ClassNotFoundException: net.kencochrane.raven.log4j.SentryAppender
    
but after put it into that lib folder, another error appear:

    log4j: Class name: [net.kencochrane.raven.log4j.SentryAppender]
    log4j:ERROR Could not create an Appender. Reported error follows.
    java.lang.ClassCastException: net.kencochrane.raven.log4j.SentryAppender cannot be cast to org.apache.log4j.Appender

Sure, there is no `log4j-*.jar` in the `lib` folder:

    ls -l /usr/local/youtrack/lib/
    total 88
    -rw-r--r-- 1 root root 79444 Jan  7 14:13 raven-6.0.0.jar
    -rw-r--r-- 1 root root  6798 Jan  7 14:35 raven-log4j-6.0.0.jar

Why and where was it loaded twice?

**Comment by tkaemming** [comment]
I spent a bit of time this morning experimenting with this and I also ran into the same issue that you did. We're not all that familiar with YouTrack and since the project isn't open source, we're limited in the level of support we can provide here. I'd suggest you contact their support, since they'll have visibility into the code that could be causing this to happen.

One thing worth noting is that you'll still need to include manually add the additional dependencies of both raven (https://github.com/getsentry/raven-java/tree/master/raven#manual-dependency-management) and raven-log4j (https://github.com/getsentry/raven-java/tree/master/raven-log4j#manual-dependency-management) that are not already included by YouTrack (e.g. Jackson, Guava, etc.) since we don't assemble or shade these dependencies with the raven JARs. I don't that think this would be causing the issue, though.

Also, from what I could tell, log4j was also initialized twice by the application (log line: `Init web application log4j location: /tmp/youtrack-example/log4j.xml`.) The first invocation would always fail with a `ClassCastException`, while the second would fail to initialize a `Raven` instance via the `RavenFactory` (included below.) Both using the [automatically registered factory provided by `ServiceLoader`](https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/net/kencochrane/raven/RavenFactory.java#L18) and explicitly providing a factory yield the same result.

```
log4j:ERROR An exception occurred during the creation of a Raven instance
java.lang.IllegalStateException: Couldn't create a raven instance for 'Dsn{uri=http://localhost/}'
        at net.kencochrane.raven.RavenFactory.ravenInstance(RavenFactory.java:93)
        at net.kencochrane.raven.log4j.SentryAppender.initRaven(SentryAppender.java:133)
        at net.kencochrane.raven.log4j.SentryAppender.activateOptions(SentryAppender.java:122)
        at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
        at org.apache.log4j.xml.DOMConfigurator.parseAppender(DOMConfigurator.java:295)
        at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(DOMConfigurator.java:176)
        at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(DOMConfigurator.java:191)
        at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(DOMConfigurator.java:523)
        at org.apache.log4j.xml.DOMConfigurator.parseRoot(DOMConfigurator.java:492)
        at org.apache.log4j.xml.DOMConfigurator.parse(DOMConfigurator.java:1006)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:872)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:755)
        at jetbrains.mps.webr.runtime.servlet.ServletUtil.configureLog4J(ServletUtil.java:124)
        at jetbrains.charisma.main.ServletImpl.init(ServletImpl.java:30)
        at javax.servlet.GenericServlet.init(GenericServlet.java:244)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:612)
        at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:468)
        at org.eclipse.jetty.servlet.ServletHolder.ensureInstance(ServletHolder.java:763)
        at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:748)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at jetbrains.youtrack.standalone.instrumentation.InstrumentingServer.handle(InstrumentingServer.java:40)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
```

I'm going to close this out because I can't imagine us making more progress without sources to walk through (and even then, this seems to be more of an issue with YouTrack then Raven.) If you come across a resolution for this, let us know.
