### ISSUE TITLE
raven-log4j2 has exception at shutdown

### ISSUE THREAD

**Issue by aiyanbo** [getsentry/raven-java#173]
```
2016-01-15 15:27:19,272 ERROR An exception occurred while closing the Raven connection java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
	at java.lang.Runtime.removeShutdownHook(Runtime.java:239)
	at net.kencochrane.raven.connection.AsyncConnection.close(AsyncConnection.java:92)
	at net.kencochrane.raven.Raven.closeConnection(Raven.java:112)
	at net.kencochrane.raven.log4j2.SentryAppender.stop(SentryAppender.java:303)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.stop(AbstractConfiguration.java:237)
	at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:224)
	at org.apache.logging.log4j.core.LoggerContext$1.run(LoggerContext.java:185)
	at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry$1.run(DefaultShutdownCallbackRegistry.java:100)
	at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.run(DefaultShutdownCallbackRegistry.java:74)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by tkaemming** [comment]
This has already been ticketed here: #167.

It should be harmless, but it's on the roadmap to get fixed in the future.

**Comment by aiyanbo** [comment]
@tkaemming Thanks!

It should be harmless, so I was ignored the exception.
