### ISSUE TITLE
Critical issue at sending org.mozilla.javascript.JavaScriptException

### ISSUE THREAD

**Issue by AlexTrotsenko** [getsentry/raven-java#215]
That is what `android.util.Log.e(tag, log, t)` gives me. It contains JavaScript stack trace:

```
E/AsExecutor: Error at running JS: 
org.mozilla.javascript.JavaScriptException: Error: TEST error in call-back of the 'lib/messages/inbox' (messages/inbox#4)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1018)
    at script(messages/inbox:4)
    at script.combineMessages(lib/messages/inbox:179)
    at script(lib/async:454)
    at script(lib/async:444)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
    at org.mozilla.javascript.NativeArray.iterativeMethod(NativeArray.java:1635)
    at org.mozilla.javascript.NativeArray.execIdCall(NativeArray.java:330)
    at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:101)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1479)
    at script(lib/async:46)
    at script(lib/async:443)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3282)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
    at com.spotme.android.appscripts.AsExecutor$AppScriptsFunctionContainer$1$1.run(AsExecutor.java:287)
    at com.spotme.android.appscripts.utils.LoggingRunnableDecorator.run(LoggingRunnableDecorator.java:26)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
```

Following is what I see on the Sentry web-site. It contains no JavaScript stack trace at all:

```
org.mozilla.javascript.JavaScriptException: Error: TEST error in call-back of the 'lib/messages/inbox' (messages/inbox#4)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1018)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
    at org.mozilla.javascript.NativeArray.iterativeMethod(NativeArray.java:1635)
    at org.mozilla.javascript.NativeArray.execIdCall(NativeArray.java:330)
    at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:101)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1479)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3282)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
    at com.spotme.android.appscripts.AsExecutor$AppScriptsFunctionContainer$1$1.run(AsExecutor.java:287)
    at com.spotme.android.appscripts.utils.LoggingRunnableDecorator.run(LoggingRunnableDecorator.java:26)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
```

As our app is using JS a lot, having no JS stackstraces means no error reporting at all!

I quickly looked in the code and I see, that `android.util.android.util.Log.getStackTraceString` uses 
`java.lang.Throwable#printStackTrace(java.io.PrintWriter)` when sentry `Raven` calls `java.lang.Throwable#getStackTrace` inside the `SentryException.SentryException(java.lang.Throwable, java.lang.StackTraceElement[])`

I also looked into raw JSON, but there is nothing related to JS:
http://pastie.org/10867870

**Comment by AlexTrotsenko** [comment]
Pinging @tkaemming  and @bretthoerner as you knows more about inner implementation of Java Raven.

**Comment by bretthoerner** [comment]
@AlexTrotsenko is there any way you could provide a minimal reproducible example?

`printStackTrace` and `getStackTrace` both get their stacktrace from the same (parameterless) private method `getOurStackTrace`... so I think something more funny is going on here, I'd like to use a debugger to dig in.
