### ISSUE TITLE
RavenContextTest.testActivateDeactivate failing on master

### ISSUE THREAD

**Issue by mikeclarke** [getsentry/raven-java#240]
I'm getting this code failure running tests on master (just running `mvn test`).

```
Tests run: 202, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 8.565 sec <<< FAILURE! - in TestSuite
testActivateDeactivate(com.getsentry.raven.RavenContextTest)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: an empty collection
     but: <[com.getsentry.raven.RavenContext@2e3fc542, com.getsentry.raven.RavenContext@6580cfdd]>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at com.getsentry.raven.RavenContextTest.testActivateDeactivate(RavenContextTest.java:22)


Results :

Failed tests:
  RavenContextTest.testActivateDeactivate:22
Expected: an empty collection
     but: <[com.getsentry.raven.RavenContext@2e3fc542, com.getsentry.raven.RavenContext@6580cfdd]>

Tests run: 202, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by tkaemming** [comment]
Proposed fix is here: GH-238
