### ISSUE TITLE
[ERROR] usage of Raven-log4j

### ISSUE THREAD

**Issue by hustcc** [getsentry/raven-java#241]
I want to use sentry to collect java exception which is not `try ... catch` by code. so I used example [here](https://github.com/getsentry/raven-java-examples/tree/master/raven-java-log4j-example) to test it.

And in the demo, I remove the `try ... catch` sa below:

```java
package com.getsentry.example;

import org.apache.log4j.Logger;

public class Application
{
    private static final Logger logger = Logger.getLogger(Application.class);

    public static void main(String[] args)
    {
        // try {
            int example = 1 / 0;
        // } catch (Exception e) {
            // logger.error("Caught exception!", e);
        // }
    }
}
```

then `mvn compile exce:java`, error below:
```
[INFO] --- exec-maven-plugin:1.4.0:java (default-cli) @ raven-java-log4j-example
 ---
[com.getsentry.example.Application.main()] INFO com.getsentry.raven.DefaultRaven
Factory - Using an HTTP connection to Sentry.
[WARNING]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArithmeticException: / by zero
        at com.getsentry.example.Application.main(Application.java:12)
        ... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.917 s
[INFO] Finished at: 2016-08-08T16:16:48+08:00
[INFO] Final Memory: 11M/220M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:java (d
efault-cli) on project raven-java-log4j-example: An exception occured while exec
uting the Java class. null: InvocationTargetException: / by zero -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal o
rg.codehaus.mojo:exec-maven-plugin:1.4.0:java (default-cli) on project raven-jav
a-log4j-example: An exception occured while executing the Java class. null
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: org.apache.maven.plugin.MojoExecutionException: An exception occured
while executing the Java class. null
        at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:345)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:207)
        ... 20 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArithmeticException: / by zero
        at com.getsentry.example.Application.main(Application.java:12)
        ... 6 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception
[Thread-1] INFO com.getsentry.raven.connection.AsyncConnection - Automatic shutd
own of the async connection
[Thread-1] INFO com.getsentry.raven.connection.AsyncConnection - Gracefully shut
down sentry threads.
[Thread-1] INFO com.getsentry.raven.connection.AsyncConnection - Shutdown finish
ed.
```
retain the `try ... catch`, the demo run well. but remove `try ... catch`, it can not work. 
How to solve it ?

**Comment by bretthoerner** [comment]
Hello,

That's because an uncaught exception in `main` crashes the program (which `mvn` is attempting to run, so it throws an `InvocationTargetException`).

Raven can't do anything itself to capture uncaught exceptions, you'll need to wrap your code at some level with a `try`/`catch` in order to capture exceptions. You could try using Java's `Thread.setUncaughtExceptionHandler` https://docs.oracle.com/javase/6/docs/api/java/lang/Thread.html#setUncaughtExceptionHandler

**Comment by hustcc** [comment]
ok, thx very much, I‘m a new bee in Java. In python raven, it can catch all the exception which is not wrapped by `try .. catch`. 
So i need to do something to catch all the exception.

**Comment by bretthoerner** [comment]
So this doesn't seem to work inside of Maven (probably because it messes with the execution somehow) but it should work inside a "real app."

```java
package com.getsentry.example;

import org.apache.log4j.Logger;

public class Application
{
    private static final Logger logger = Logger.getLogger(Application.class);

    public static void main(String[] args)
    {
        setupUncaughtExceptionHandler();

        int example = 1 / 0;
    }

    private static void setupUncaughtExceptionHandler() {
        final Thread.UncaughtExceptionHandler defaultUncaughtExceptionHandler = Thread.getDefaultUncaughtExceptionHandler();
        Thread.setDefaultUncaughtExceptionHandler(new Thread.UncaughtExceptionHandler() {
            public void uncaughtException(Thread t, Throwable e) {
                System.out.println("\n\nHI\n\n=");
                logger.error("An uncaught exception occurred: ", e);
                if (defaultUncaughtExceptionHandler != null) {
                    defaultUncaughtExceptionHandler.uncaughtException(t, e);
                }
            }
        });
    }
}
```
