### ISSUE TITLE
On-premise sentry installation and SSLHandshakeException

### ISSUE THREAD

**Issue by dementiev** [getsentry/raven-java#242]
We run on-premise sentry installation with self-signed ssl certificate.
While trying to send message to Sentry server I receive next error:
```
raven-pool-1-thread-2 send AbstractConnection An exception due to the connection occurred, a lockdown will be initiated.
net.kencochrane.raven.connection.ConnectionException: An exception occurred while submitting the event to the sentry server.
	at net.kencochrane.raven.connection.HttpConnection.doSend(HttpConnection.java:131)
	at net.kencochrane.raven.connection.AbstractConnection.send(AbstractConnection.java:78)
	at net.kencochrane.raven.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:137)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative names present
	at net.kencochrane.raven.connection.HttpConnection.doSend(HttpConnection.java:120)
	... 5 more
Caused by: java.security.cert.CertificateException: No subject alternative names present
	... 6 more
```
Thanks in advance for ideas how I can fix it.

Best,
Dmitry

**Comment by bretthoerner** [comment]
I think you'll need to add your self-signed cert to the Java keystore on each machine that needs to speak to Sentry. For an example, check the bottom of this page: https://docs.getsentry.com/hosted/ssl/

Once it's in the Keystore, the JVM on that machine should be OK with talking to your server.
