### ISSUE TITLE
NPE if raven. jar is in web app classpath with no loggers configured

### ISSUE THREAD

**Issue by foal** [getsentry/raven-java#272]
If raven-7.8.0.jar is in classpath without loggers configured:

18:24:40.468 [http-nio-8080-exec-3] ERROR c.g.r.s.RavenServletRequestListener - Error clearing RavenContext state.
java.lang.NullPointerException: No stored Raven instance is available to use. You must construct a Raven instance before using the static Raven methods.
	at com.getsentry.raven.Raven.getStoredInstance(Raven.java:208)
	at com.getsentry.raven.servlet.RavenServletRequestListener.requestDestroyed(RavenServletRequestListener.java:31)
	at org.apache.catalina.core.StandardContext.fireRequestDestroyEvent(StandardContext.java:6025)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:186)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

BTW in is in local environment with only console logging

**Comment by foal** [comment]
See already fixed. Great :)

**Comment by singharpit1991** [comment]
How?

**Comment by foal** [comment]
7.8.1 version
