### ISSUE TITLE
Logback - configuration issue / NPE when exception logged

### ISSUE THREAD

**Issue by mstawick** [getsentry/raven-java#278]
I'm trying to setup Sentry (raven-logback, 7.8.0) with logback / Spring Boot. I followed the documentation, check that I have proper logback version, etc.

As soon as something is to be logged to Sentry, I get this exception:

```
.10:50:41.451 [http-nio-8080-exec-1] ERROR c.g.r.s.RavenServletRequestListener - Error clearing RavenContext state. 
java.lang.NullPointerException: No stored Raven instance is available to use. You must construct a Raven instance before using the static Raven methods.
	at com.getsentry.raven.Raven.getStoredInstance(Raven.java:208) ~[raven-7.8.0.jar:na]
	at com.getsentry.raven.servlet.RavenServletRequestListener.requestDestroyed(RavenServletRequestListener.java:31) ~[raven-7.8.0.jar:na]
	at org.apache.catalina.core.StandardContext.fireRequestDestroyEvent(StandardContext.java:5936) [catalina.jar:8.0.21]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:187) [catalina.jar:8.0.21]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.21]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.21]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.21]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) [catalina.jar:8.0.21]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) [tomcat-coyote.jar:8.0.21]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668) [tomcat-coyote.jar:8.0.21]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.21]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1517) [tomcat-coyote.jar:8.0.21]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1474) [tomcat-coyote.jar:8.0.21]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.21]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
```

Am I supposed to do some additional Sentry initialisation, except for logback.xml? 

Thanks

UPDATE:
Tried downgrading to 7.7.0 - above exception is not logged, but still nothing gets logged to Sentry.

UPDATE2:
Interestingly it started working after I've added:
```
<filter class="ch.qos.logback.classic.filter.ThresholdFilter">
    <level>WARN</level>
</filter>
```

to Sentry appender configuration.

**Comment by bretthoerner** [comment]
Sorry, this was fixed here but I haven't pushed a release, I'll do that now: https://github.com/getsentry/raven-java/commit/9c85fe81ec43493f43b786a92ae30385ff4fef8a

That said, your second update is curious. What does your full logback config look like now? What was the log level set to before?

**Comment by mstawick** [comment]
Before, I went straight with example from docs:
```
<appender name="Sentry" class="com.getsentry.raven.logback.SentryAppender">
    <dsn>...snip...</dsn>
</appender>

<root>
    <level value="ERROR"/>
    <appender-ref ref="consoleAppender"/>
    <appender-ref ref="Sentry" />
</root>
```

After the change:
```
    <appender name="Sentry" class="com.getsentry.raven.logback.SentryAppender">
        <dsn>...snip...</dsn>
        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>WARN</level>
        </filter>
    </appender>

    <root>
        <level value="ERROR"/>
        <appender-ref ref="consoleAppender"/>
        <appender-ref ref="Sentry" />
    </root>
```

**Comment by bretthoerner** [comment]
So when you logged something from your own app at `ERROR` level it wasn't going to Sentry?

**Comment by bretthoerner** [comment]
Version `7.8.1` is being distributed on Maven Central and will fix the annoying log message.

**Comment by mstawick** [comment]
Yes, I was getting above exception and nothing was logged. Thanks for releasing so fast.
