### ISSUE TITLE
 com.getsentry.raven.connection.ConnectionException "Creation of this event was denied due to rate limiting"

### ISSUE THREAD

**Issue by luckydonald** [getsentry/raven-java#291]
This is spamming my logfiles
```java
com.getsentry.raven.connection.ConnectionException: {"error_name":"rate_limit","error":"Creation of this event was denied due to rate limiting"}
     at com.getsentry.raven.connection.HttpConnection.doSend(HttpConnection.java:157)
     at com.getsentry.raven.connection.AbstractConnection.send(AbstractConnection.java:86)
     at com.getsentry.raven.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:164)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Server returned HTTP response code: 429 for URL: https://sentry.io/api/129182/store/
     at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
     at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
     at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
     at com.getsentry.raven.connection.HttpConnection.doSend(HttpConnection.java:149)
     ... 5 more
```
Maybe fail silently?

**Comment by bretthoerner** [comment]
I'm going to make this raise a better/named exception so that it can be more easily filtered in people's logging framework of choice.

**Comment by bretthoerner** [comment]
Think #297 will help alleviate most of this, too.

**Comment by luckydonald** [comment]
Probably helpful if there could be a short tutorial how to silent that than (with the recomment logging setup).

**Comment by bretthoerner** [comment]
I think muting a specific logger is outside the scope of `raven-java`, that is a standard feature of each logging framework and is different for each.

For example, log4j: https://stackoverflow.com/questions/4972954/how-to-disable-loggers-of-a-class-or-of-whole-package

**Comment by luckydonald** [comment]
a shame it is different for each.
But as you have a setup instructions for different frameworks, this could be added for each. Not emitting such logs, I'd call that a feature.
I mean rate limiting is an error sentry introduced, and using that reporting system should be failing gracefully. Or at least have that as an option.

**Comment by bretthoerner** [comment]
@luckydonald out of curiosity could you post your logging config?

**Comment by bretthoerner** [comment]
In the latest release (`7.8.3`) there is a new logger used specifically for Events that are dropped due to a lockdown, you can disable this logger in your logging framework of choice: `com.getsentry.raven.Raven.lockdown`

Let me know if you try this and have any issues. Note that we still log when a lockdown begins (or increases in backoff time), but with that logger above disabled you shouldn't receive log spam for *each* Event that fails.

**Comment by bretthoerner** [comment]
Quick update, my change didn't work with `AsyncConnection`, that was fixed here: https://github.com/getsentry/raven-java/commit/a74e8d74dbcadc0b7cf0098d01728677ee2cfe6f

Will be in the next release.
