### ISSUE TITLE
Could not initialize class org.apache.log4j.LogManager with Kafka

### ISSUE THREAD

**Issue by peay** [getsentry/raven-java#395]
I've been trying to use the log4j appender with Kafka 0.10.1.1, but I am getting 

```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.apache.log4j.LogManager
	at org.apache.log4j.Logger.getLogger(Logger.java:104)
	at kafka.utils.Logging$class.logger(Logging.scala:24)
	at kafka.Kafka$.logger$lzycompute(Kafka.scala:29)
	at kafka.Kafka$.logger(Kafka.scala:29)
	at kafka.utils.Logging$class.fatal(Logging.scala:115)
	at kafka.Kafka$.fatal(Kafka.scala:29)
	at kafka.Kafka$.main(Kafka.scala:72)
	at kafka.Kafka.main(Kafka.scala)
```

without more information. I've added the following JARs to Kafka's classpath:

```
slf4j-api-1.7.24.jar
jackson-core-2.8.7.jar
raven-8.0.2.jar
raven-log4j-8.0.3.jar
```

Output of running with `-verbose` (https://pastebin.com/kg1nqe9M)  has

```
[Loaded org.apache.log4j.LogManager from file:/opt/kafka/libs/log4j-1.2.17.jar]
```

Any idea? I am wondering if there could be a static initialisation issue somewhere whose exception would get swallowed, but not sure how to debug that.

**Comment by bretthoerner** [comment]
Hey @peay 

That's odd. So this is the Kafka line it's blowing up on: https://github.com/apache/kafka/blob/0.10.1/core/src/main/scala/kafka/utils/Logging.scala#L24

And these seem to be the logging jars included in your Kafka version:

```
kafka_2.10-0.10.1.1/libs ls -1 | grep -E "(slf4j|log4j)"

kafka-log4j-appender-0.10.1.1.jar
log4j-1.2.17.jar
slf4j-api-1.7.21.jar
slf4j-log4j12-1.7.21.jar
```

Long shot: Have you tried not including your own `slf4j-api-1.7.24.jar` since there is a different version already in Kafka?

And then number 2 here has details on `NoClassDefFoundError`: http://stackoverflow.com/a/5756989

This is definitely an odd one...

**Comment by bretthoerner** [comment]
So this worked for me:

I downloaded Kafka 0.10.1.1 and put the following jars into the `libs/` dir:

```
-rw-r--r--@ 1 brett  staff   8.4K May  9 14:14 raven-log4j-8.0.3.jar
-rw-r--r--@ 1 brett  staff   134K May  9 14:14 raven-8.0.3.jar
-rw-r--r--@ 1 brett  staff   276K May  9 14:15 jackson-core-2.8.7.jar
```

I then changed these lines in `config/log4j.properties`:

```
log4j.rootLogger=INFO, stdout, Sentry

log4j.appender.Sentry=com.getsentry.raven.log4j.SentryAppender
log4j.appender.Sentry.threshold=WARN
```

Then I ran the Kafka broker:

`SENTRY_DSN="https://mydsn" ./bin/kafka-server-start.sh config/server.properties`

Granted, I haven't started ZK or anything on my local machine, so I immediately received a ton of errors. But those errors went to Sentry as expected:

![](https://i.imgur.com/ffsPN00.png)

**Comment by peay** [comment]
Thanks for checking -- the fact that it worked for you made me go over all non-standard things that I had in this environment, and I finally figured out the issue.

The above issue occurs because I had

```
export SENTRY_TAGS=component=kafka
```

in my environment, which should be `export SENTRY_TAGS=component:kafka`, with a colon instead of `=`.

This is quite confusing that it would fail with a `NoClassDefFoundError` in this case, although I assume that raven does throw but that exception probably gets swallowed somehow.

**Comment by bretthoerner** [comment]
Yeah, it looks like Sentry throws this (I'm not sure what Kafka is doing with it):

```
[WARNING] 
java.lang.ExceptionInInitializerError
	at org.apache.log4j.Logger.getLogger(Logger.java:104)
	at io.sentry.example.Application.<clinit>(Application.java:7)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Invalid tags entry: foo=bar
	at io.sentry.util.Util.parseTags(Util.java:46)
	at io.sentry.log4j.SentryAppender.setTags(SentryAppender.java:365)
	at io.sentry.log4j.SentryAppender.lazyInit(SentryAppender.java:153)
	at io.sentry.log4j.SentryAppender.activateOptions(SentryAppender.java:210)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:842)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	... 8 more
```
